name: Python workflow

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: python:3.10-bullseye
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install psql
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client
      - name: Create test database and user
        env:
          PGUSER=postgres
          PGPASSWORD=postgres
          PEEP_DB_NAME=peep_python
          PEEP_USER=peep_user
          PEEP_PASSWORD=peep_password
        run: |
          psql -h $PGUSER -U $PGPASSWORD -c "create database $PEEP_DB_NAME"
          psql -h $PGUSER -U $PGPASSWORD -c "create user $PEEP_USER"
          psql -h $PGUSER -U $PGPASSWORD -c "alter user $PEEP_USER with password $PEEP_PASSWORD"
          psql -h $PGUSER -U $PGPASSWORD -c "grant all privileges on database $PEEP_DB_NAME to $PEEP_USER"
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: pytest lambdas/tests/